test steps

diff --git a/azure-pipelines-delete.yml b/azure-pipelines-delete.yml
--- a/azure-pipelines-delete.yml
+++ b/azure-pipelines-delete.yml
@@ -20,14 +20,56 @@ steps:
 - script: pip install pip-audit
   displayName: Install pip-audit
 
-# run pip-audit scan on each package in the requirements_vulnerable.txt file
-# if any passes, fail the step - do this to ensure we do not mistakenly delete any non-CVE libraries as the feed is immutable
+# # run pip-audit scan on each package in the requirements_vulnerable.txt file
+# # if any passes, fail the step - do this to ensure we do not mistakenly delete any non-CVE libraries as the feed is immutable
+# - script: |
+#     #!/usr/bin/env bash
+#     set -euo pipefail
+
+#     REQ_FILE=requirements_vulnerable.txt
+#     ANY_PASS=0
+
+#     # Read all lines into an array first
+#     mapfile -t packages < "$REQ_FILE"
+
+#     for line in "${packages[@]}"; do
+#       [[ -z "$line" || "$line" == \#* ]] && continue
+
+#       # create a temporary one-line requirements file
+#       tmpfile=$(mktemp)
+#       echo "$line" > "$tmpfile"
+
+#       # run pip-audit on that single package line
+#       if pip-audit -r "$tmpfile" >/dev/null 2>&1; then
+#         echo "$line PASSED → failing step"
+#         ANY_PASS=1
+#       else
+#         echo "$line FAILED → as expected"
+#       fi
+
+#       rm -f "$tmpfile"
+#     done
+
+#     if [ "$ANY_PASS" -eq 1 ]; then
+#       echo "At least one package passed audit → failing step"
+#       exit 1
+#     fi
+
+#     echo "✔ All dependencies failed audit as required"
+#   displayName: Validate Only Failed Scanned Packages
+
+
+# authenticate to azure artifact feed
+- task: PipAuthenticate@1
+  inputs:
+    artifactFeeds: cdporgfeed
+    # artifactFeeds: $(FEED_NAME)
+
+# upload directly to org feed
 - script: |
-    #!/usr/bin/env bash
     set -euo pipefail
 
     REQ_FILE=requirements_vulnerable.txt
-    ANY_PASS=0
 
     # Read all lines into an array first
     mapfile -t packages < "$REQ_FILE"
@@ -35,57 +77,21 @@ steps:
     for line in "${packages[@]}"; do
       [[ -z "$line" || "$line" == \#* ]] && continue
 
-      # create a temporary one-line requirements file
-      tmpfile=$(mktemp)
-      echo "$line" > "$tmpfile"
+      pkg=$(echo "$line" | cut -d'=' -f1)
+      ver=$(echo "$line" | cut -d'=' -f3)
+      
+      echo "$pkg"
+      echo "$ver"
 
-      # run pip-audit on that single package line
-      if pip-audit -r "$tmpfile" >/dev/null 2>&1; then
-        echo "$line PASSED → failing step"
-        ANY_PASS=1
-      else
-        echo "$line FAILED → as expected"
-      fi
-
-      rm -f "$tmpfile"
-    done
-
-    if [ "$ANY_PASS" -eq 1 ]; then
-      echo "❌ At least one package passed audit → failing step"
-      exit 1
-    fi
-
-    echo "✔ All dependencies failed audit as required"
-  displayName: Validate Only Failed Scanned Packages
-
-# - script: |
-#     set -o pipefail
-
-#     AUDIT_OUTPUT=$(pip-audit -r requirements.txt 2>&1 || true)
-
-#     # Escape newlines so Azure can store it
-#     AUDIT_OUTPUT_ESCAPED=$(echo "$AUDIT_OUTPUT" | sed ':a;N;$!ba;s/\n/\\n/g')
-
-#     echo "##vso[task.setvariable variable=PIP_AUDIT_OUTPUT]$AUDIT_OUTPUT_ESCAPED"
-
-#     # Fail the step if vulnerabilities exist
-#     pip-audit -r requirements.txt
-#   displayName: Enforce security gate and capture output
-
-
-# # authenticate to azure artifact feed
-# - task: PipAuthenticate@1
-#   inputs:
-#     artifactFeeds: $(FEED_NAME)
-
-# # upload directly to org feed
-# - script: |
-#     twine upload \
-#       --skip-existing \
-#       --repository-url https://pkgs.dev.azure.com/$(ORG_NAME)/_packaging/$(FEED_NAME)/pypi/upload/ \
-#       -u __token__ \
-#       -p $SYSTEM_ACCESSTOKEN \
-#       downloaded_packages/*
-#   displayName: Upload packages to Azure Artifacts feed
-#   env:
-#     SYSTEM_ACCESSTOKEN: $(System.AccessToken)
+      # az artifacts package delete \
+      # --organization "$ORG_URL" \
+      # --project "$PROJECT" \
+      # --feed "$FEED" \
+      # --package-name "$pkg" \
+      # --package-type "PyPI" \
+      # --version "$ver" \
+      # --yes
+  displayName: Delete Vulnerable Package from Azure Artifacts feed
+  condition: succeeded("Install pip-audit")
+  env:
+    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
