fix syntax

diff --git a/azure-pipelines-push.yml b/azure-pipelines-push.yml
--- a/azure-pipelines-push.yml
+++ b/azure-pipelines-push.yml
@@ -33,32 +33,32 @@ steps:
 - script: pip install pip-audit
   displayName: Install pip-audit
 
-# # run pip-audit scan and generate security report
-# - script: |
-#     mkdir -p audit-report
+# run pip-audit scan and generate security report
+- script: |
+    mkdir -p audit-report
 
-#     if [ -s requirements.txt ]; then
-#       echo "Running pip-audit..."
-#       pip-audit \
-#         -r requirements.txt \
-#         --format json \
-#         --output audit-report/pip-audit-report.json || true
-#     else
-#       echo "No new dependencies" > audit-report/pip-audit-report.json
-#     fi
-#   displayName: Run pip-audit and generate report
+    if [ -s requirements.txt ]; then
+      echo "Running pip-audit..."
+      pip-audit \
+        -r requirements.txt \
+        --format json \
+        --output audit-report/pip-audit-report.json || true
+    else
+      echo "No new dependencies" > audit-report/pip-audit-report.json
+    fi
+  displayName: Run pip-audit and generate report
 
-# # publish security report json to pipeline artifact
-# - task: PublishPipelineArtifact@1
-#   displayName: Publish pip-audit report
-#   inputs:
-#     targetPath: audit-report
-#     artifact: pip-audit-report
+# publish security report json to pipeline artifact
+- task: PublishPipelineArtifact@1
+  displayName: Publish pip-audit report
+  inputs:
+    targetPath: audit-report
+    artifact: pip-audit-report
 
-# # ensure pipeline fails in the event of vulnerabilities
-# - script: |
-#     pip-audit -r requirements.txt
-#   displayName: Enforce security gate
+# ensure pipeline fails in the event of vulnerabilities
+- script: |
+    pip-audit -r requirements.txt
+  displayName: Enforce security gate
 
 - script: |
     set -o pipefail
@@ -71,7 +71,8 @@ steps:
     echo "##vso[task.setvariable variable=PIP_AUDIT_OUTPUT]$AUDIT_OUTPUT_ESCAPED"
 
     # Fail the step if vulnerabilities exist
-    echo "$AUDIT_OUTPUT" | grep -q "Found .* known vulnerability" && exit 1 || exit 0
+    pip-audit -r requirements.txt
+    # echo "$AUDIT_OUTPUT" | grep -q "Found .* known vulnerability" && exit 1 || exit 0
   displayName: Enforce security gate and capture output
 
 # send Slack notification (reflects success or failure of the pipeline)
@@ -88,29 +89,23 @@ steps:
       PIPELINE_STATUS="failed"
     fi
 
+    # AUDIT_OUTPUT=$(printf "%b" "$(PIP_AUDIT_OUTPUT)")
+    AUDIT_OUTPUT=$(printf "%b" "$(PIP_AUDIT_OUTPUT)" \
+    | tr -d '\r' \
+    | sed 's/^[[:space:]]*//')
 
-    AUDIT_OUTPUT=$(printf "%b" "$(PIP_AUDIT_OUTPUT)")
 
     # Set message text based on pipeline status
     if [ "$PIPELINE_STATUS" == "succeeded" ]; then
       PIPELINE_MESSAGE="✅ Daily Private Package Security Scan succeeded! Check the details and logs here: <${PIPELINE_URL}|Pipeline> | <${ARTIFACT_URL}|Scan Artifact>"
     else
-      PIPELINE_MESSAGE="🚨 Daily Private Package Security Scan failed!
-
-      *pip-audit output:*
+      PIPELINE_MESSAGE="🚨 Daily Private Package Security Scan failed!*pip-audit output:*
       \`\`\`
       $AUDIT_OUTPUT
       \`\`\`
 
       <${PIPELINE_URL}|Pipeline> | <${ARTIFACT_URL}|Scan Artifact>"
     fi
-
-    # # Set message text based on pipeline status
-    # if [ "$PIPELINE_STATUS" == "succeeded" ]; then
-    #   PIPELINE_MESSAGE="✅ Daily Private Package Security Scan succeeded! Check the details and logs here: <${PIPELINE_URL}|Pipeline> | <${ARTIFACT_URL}|Scan Artifact>"
-    # else
-    #   PIPELINE_MESSAGE="🚨 Daily Private Package Security Scan failed! Check the details and logs here: <${PIPELINE_URL}|Pipeline> | <${ARTIFACT_URL}|Scan Artifact>"
-    # fi
 
     # Send the Slack notification with both pipeline and artifact URLs as hyperlinks
     curl -X POST -H 'Content-type: application/json' --data "{
